### ISSUE TITLE
Basic Item API Routes

### ISSUE THREAD

**Issue by liam-strand** [JumboCode/theatre-at-first#29]
# Summary

Ok, you should have a good foundation at this point. Now we're going to start working on the site proper! This is a backend ticket, so you will be developing a set of Route Handlers (formerly known as API routes) to access and modify items. 

## Deliverables

- [x] Familiarize yourself with the [NEXT docs](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) on Route Handlers
- [x] Create an API route called `add-item` that has a POST handler
- [x] #34
- [x] Create an API route called `get-item` that has a GET handler
- [x] This handler should parse parse out an item ID from JSON, get the item with the corresponding ID from the database, and return that item's info in the response.
- [x] Open a PR and request review from @anott03 and @liam-strand.

## Where to get help

Same places as always :)

**Comment by teddyh-io** [comment]
@liam-strand @anott03 
Hey, is there a documentation of some kind I can read over to understand Drizzle further? My partner and I are having trouble understanding how to add items to the database. I saw in one file in the repo that i can do a fetch to /api but I am not able to get this to work on my machine.
