### ISSUE TITLE
Broken and Missing Stuff Thread

### ISSUE THREAD

**Issue by liam-strand** [JumboCode/theatre-at-first#88]
## Please comment below with any issues you find in the site

These include...

- Missing features
- Missing links
- Broken styling
- Typos
- Stuff that just feels wonky
- JavaScript/TypeScript runtime errors/warnings
- Debug `console.log`s
- Especially gnarly code style
- Undocumented tricky bits of code

Please be ***specific*** and ***concise*** in your description. Here are some examples:

- [ ] The item tiles on the inventory view should link to detail pages
- [ ] Landing page reacts poorly to mobile viewing
- [ ] There is debug output on the "add an item" page
- [ ] The admin control page could have a better route

Notice that those are all checkboxes. Please do that sort of list so that we can easily convert them into GitHub issues. You can do a checkbox list by hitting the "task list" button in the editor or by typing `- [ ] yourtexthere` in the text field (yay markdown).

Additionally, please make sure you are testing on the `main` branch. Does this mean you might catch issues that are already fixed in another branch waiting to be merged? Yes, but it makes sure that we are all testing against the same baseline.

**Comment by liam-strand** [comment]
- [ ] nothing works

**Comment by danglorioso** [comment]
[ ] error when capturing picture

<img width="992" alt="Screenshot 2024-04-21 at 7 20 10 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/1181445d-23b3-4f28-82f3-43da1ed2eff9">

**Comment by brandondionisio** [comment]
- [ ] item-upload-page-test doesn't start with the "click to take a picture" box there womp womp

**Comment by danglorioso** [comment]
- [ ] error when spamming capture image button

<img width="960" alt="Screenshot 2024-04-21 at 7 22 51 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/2edb6a10-c692-4f0a-9f16-379384c0a847">

**Comment by brandondionisio** [comment]
- [ ] WRITING A LONG TEXT IN TAGS FOR item-upload-page-test GOES THROUGH THE DROP DOWN ARROW

**Comment by bell-oh** [comment]
- [ ] `inventory-viewing` page has hardcoded dummy data/ is not hooked up to database
- [ ] `item-detail-test` page is a test page
- [ ] `image-capture-and-upload-component` speaking in demonic tongues when u try to take a pic
- [ ] `item-upload-page-test` has hardcoded data

**Comment by danglorioso** [comment]
- [ ] item page for an ID item that doesn't exist is bad 
i.e. http://localhost:3000/item/283467821634

<img width="965" alt="Screenshot 2024-04-21 at 7 27 59 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/32987fff-5d4e-47e8-9a21-d68913edf55a">

**Comment by brandondionisio** [comment]
- [ ] Expected behavior??
![image](https://github.com/JumboCode/theatre-at-first/assets/145251710/c671e3d7-7087-4b23-9c0b-62f622edb1f3)

**Comment by pmorganelli** [comment]
-Naming of folders should be universal (all camel case or all with en-dashes)
-Running the dev server after pulling from main doesn't work correctly 
-Search Item API (searching part) does not function on the inventory viewing page
-Inventory viewing tags are hard coded (dummy data, replace this with something else)

**Comment by bell-oh** [comment]
- [ ] back to inventory page button doesn't work
<img width="286" alt="Screenshot 2024-04-21 at 7 33 03 PM" src="https://github.com/JumboCode/theatre-at-first/assets/103330338/c1c4f966-c7a0-4775-88be-17e6faa25350">

**Comment by danglorioso** [comment]
- [ ] duplicate tags are allowed?!

<img width="417" alt="Screenshot 2024-04-21 at 7 35 02 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/7dd3640a-e692-47ff-99f7-e1620d7bbbed">

**Comment by bell-oh** [comment]
- [ ] TODO found on `src/app/item/[id]/page.tsx` line 28: make a proper not found page
- [ ] TODO found on `src/app/item/[id]/page.tsx` line 41: load images properly

**Comment by bell-oh** [comment]
- [ ] `search-item` route is dirtyyyyyyy bc it has the backend implementation commented out

**Comment by danglorioso** [comment]
- [ ]  cannot add comment to item page

**Comment by danglorioso** [comment]
- [ ] back to inventory button on item page is not linked

**Comment by pmorganelli** [comment]
-Close button way too small when added an iframe from a youtube link
![image](https://github.com/JumboCode/theatre-at-first/assets/146687222/13ff28ba-ce78-468e-8ea7-500a1c68c055)

**Comment by ShepardRodgers** [comment]
- [ ] No landing page!!
- [ ] Demonic text when taking an image with image-capture-and-upload-component
- [ ] Search bar doesn't work for inventory-viewing
- [ ] "Unknown" tag appearing under item names in item detail view
- [ ] No images in image carousel item detail view
- [ ] All comments are the same for item detail view
- [ ] "back to inventory list", "edit", and "add" buttons don't work
- [ ]  Images not available for item detail view

**Comment by nehirozden** [comment]
- [ ]  no landing page
- [ ] image capture should not a page
- [ ] search is not hooked up to anything
- [ ] can't take photo in item-upload-page-test 
- [ ] can't go back to inventory list from item-upload-page-test
- [ ] we haven't linked the pages together
- [ ] when i do item/86 it doesn't compile says this:
 ⨯ Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
- [ ] need to make a not found page
- [ ] don't need a page for the image-capture-and-upload-component
- [ ] a lot of comments in route page of search-item
- [ ] needs comments in upload-presigned-url
- [ ] get rid of buttons??
- [ ] fix comments in literally every component .tsx file

**Comment by pmorganelli** [comment]
-No reply functionality for comments on an item
![image](https://github.com/JumboCode/theatre-at-first/assets/146687222/d59aff63-aab1-4b24-ab0c-6dcec307f233)

(its not our fault)

**Comment by ShepardRodgers** [comment]
- [ ] no item data stored for id's 1 and 2

**Comment by pmorganelli** [comment]
> * [ ]  back to inventory page button doesn't work
> 
> <img alt="Screenshot 2024-04-21 at 7 33 03 PM" width="286" src="https://private-user-images.githubusercontent.com/103330338/324292342-c1c4f966-c7a0-4775-88be-17e6faa25350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDI3MTUsIm5iZiI6MTcxMzc0MjQxNSwicGF0aCI6Ii8xMDMzMzAzMzgvMzI0MjkyMzQyLWMxYzRmOTY2LWM3YTAtNDc3NS04OGJlLTE3ZTZmYWEyNTM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjBiZmI3MmQ2MDdhZjMwNWM3NjdkMTlmZWIxMTA1YWFmYTI4N2U4ZTIyNTFhZTQ1NTA4ZDY2MDRkZTVhZjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qyANBz55HQR4zkaA3GMOyG9aoxVJOV7vVJHu2DFaEyI">

Also, broken for individual item summary pages

**Comment by pmorganelli** [comment]
-No indication of "no results found" for an item if the filters don't match
![image](https://github.com/JumboCode/theatre-at-first/assets/146687222/d90a5539-eff1-41d6-9b33-58aef34de5f3)

**Comment by brandondionisio** [comment]
- [ ] None of the buttons on this page work
![image](https://github.com/JumboCode/theatre-at-first/assets/145251710/b43ddb24-cbd2-4bd1-b0af-83fe8c091d20)

**Comment by danglorioso** [comment]
- [ ] Item image does not resize properly on mobile (may not be necessary)

<img width="459" alt="Screenshot 2024-04-21 at 7 48 20 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/366cf8ff-1125-4d97-92c4-363bbca77d80">

**Comment by danglorioso** [comment]
- [ ] Item ID out of range of int is unhandled runtime error 

<img width="1104" alt="Screenshot 2024-04-21 at 7 56 26 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/4b3051f5-05f7-4d09-abfc-ecfeee209b8e">

**Comment by danglorioso** [comment]
- [ ] When the description gets really long, weird blank sidebar on right appears until the last line

<img width="431" alt="Screenshot 2024-04-21 at 7 59 28 PM" src="https://github.com/JumboCode/theatre-at-first/assets/125602370/56f0ee3c-62b4-44e4-ab09-1f224a4bbece">

**Comment by brandondionisio** [comment]
- [ ] When there's more than three rows of tags, you can't delete the first row :(
![image](https://github.com/JumboCode/theatre-at-first/assets/145251710/d266fc02-f73f-49eb-90b1-3666e45de075)

**Comment by liam-strand** [comment]
> * [ ]  Expected behavior??
>       ![image](https://private-user-images.githubusercontent.com/145251710/324292108-c671e3d7-7087-4b23-9c0b-62f622edb1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTUxODUsIm5iZiI6MTcxMzc1NDg4NSwicGF0aCI6Ii8xNDUyNTE3MTAvMzI0MjkyMTA4LWM2NzFlM2Q3LTcwODctNGIyMy05YzBiLTYyZjYyMmVkYjFmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwMzAxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjEwMjhkYWFhZWZkNjlkYWQ0YWQxN2I1OGNhMWI3YTc3ZmJjYzUxY2ZmMTVkZmViZjY3YjdmMmUyN2Q3MmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZdYfn64XeMYXUVmqWEEOwrRitNUY-UwZsKYmvFVdFrU)

I'm going to go with yes, that is expected, @brandondionisio.
